[shell]
    # TODO unix things
    program = "wsl.exe"
    args = ["--cd", "~"]

[window]
    title = "Hello Soup!"
    dynamic_title = false

[colors.primary]
    foreground = "#abb2bf"
    # Default: "#d8d8d8"
    background = "#282c34"
    # Default: "#181818"

[colors.normal]
    black = "#181a1f"
    # Default: "#181818"
    red = "#e86671"
    # Default: "#ac4242"
    green = "#98c379"
    # Default: "#90a959"
    yellow = "#e5c07b"
    # Default: "#f4bf75"
    blue = "#61afef"
    # Default: "#6a9fb5"
    magenta = "#c678dd"
    # Default: "#aa759f"
    cyan = "#56b6c2"
    # Default: "#75b5aa"
    white = "#abb2bf"
    # Default: "#d8d8d8"

# TODO:
# [colors.dim]
    # black = "#"
    # Default: "#0f0f0f"
    # red = "#"
    # Default: "#712b2b"
    # green = "#"
    # Default: "#5f6f3a"
    # yellow = "#"
    # Default: "#a17e4d"
    # blue = "#"
    # Default: "#456877"
    # magenta = "#"
    # Default: "#704d68"
    # cyan = "#"
    # Default: "#4d7770"
    # white = "#"
    # Default: "#8e8e8e"

